### ISSUE TITLE
HTTPS tests are inaccurate for Firefox

### ISSUE THREAD

**Issue by JessePeden** [privacytests/privacytests.org#227]
On the website https://privacytests.org, Firefox is listed as not upgrading HTTP connections to HTTPS or displaying a warning for insecure sites (see the included screenshot), but it has had that ability since 2020, with the addition of HTTPS-Only mode in version 83, and it is still present today in version 131 (see the included screenshot from Firefox 131's settings page).  Documentation about the feature can be found [here](https://support.mozilla.org/en-US/kb/https-only-prefs).

### https://privacytests.org screenshot:
<img width="483" alt="Screenshot 2024-10-23 at 15 50 58" src="https://github.com/user-attachments/assets/4e71bacd-b62a-4486-a72d-aae77580c162">

### Firefox 131 screenshot:
<img width="685" alt="Screenshot 2024-10-23 at 16 00 13" src="https://github.com/user-attachments/assets/abc50d47-c073-492a-a8bb-b84f782542d1">

**Comment by arthuredelstein** [comment]
Hi Jesse, thanks for the comment. The reason you are seeing these test failures is that PrivacyTests looks at the behavior of a browser when it is set to default settings only.

It's true that Firefox offers [HTTPS-Only Mode](https://blog.mozilla.org/security/2020/11/17/firefox-83-introduces-https-only-mode/), but unfortunately that feature is disabled by default, which means it fails the `Insecure website warning` test in both Normal and Private windows.

Firefox Private mode does have [HTTPS-by-Default enabled in Private Windows](https://blog.mozilla.org/security/2021/08/10/firefox-91-introduces-https-by-default-in-private-browsing/), which means that it passes the [`Upgradable address test` for Private Windows](https://privacytests.org/private), but this feature is also not enabled in Normal windows, so Firefox fails that test in the case you point out above.

Hopefully Firefox will upgrade its default HTTPS handling in the near future so that it passes these tests!

**Comment by JessePeden** [comment]
I see.  That does make sense.  I wasn't aware that the tests only looked at default, and thought it looked at whether or not a browser was capable of protecting against each type of leak.
